### ISSUE TITLE
AI aircraft light handling improvments

### ISSUE THREAD

**Issue by JT8D-17** [mSparks43/XPlane-11-AutoATC-plugin#85] opened 2020-06-29 19:33 UTC
AI aircraft permanently have their lights on, even when parked.

More realistic handling:
- Nav lights on when aircraft under electrical power (varies by airline SOP)
- Beacon lights on before engine start until after engine shutdown
- Strobe lights on when crossing an active runway and from entering runway for takeoff to leaving runway after landing
- Taxi lights on when taxiing
- Landing lights on from entering runway to transition altitude (or 10000 feet) and vice versa for landing

**Comment by mSparks43** [comment] 2020-06-29 21:30
This is definitely a weak area that is more about how time consuming it is than how complex.

These are all set around line 743 of

https://github.com/mSparks43/XPlane-11-AutoATC-plugin/blob/master/src/AIPlanesv0.6.cpp

the crux of the issue is the different names of datarefs the csls use depending on who made them and when, and mapping them to the relevant value.

ref style 3 is xplane objects from the aircraft folder, which is completely different again.

I'd prefer to shift that entire block into a bundled and upgraded xtlua first (datarefs to use, animation logic and files), it would make maintenance/tweaking much easier and open up the door to various customizations (like attaching particles), but the priority at the moment is getting the atc components feature complete, filling out the language support, plus making/keeping everything stable.
xtlua needs quite a few more flight hours before its ready to bring in, but most of the foundations are laid now.

**Comment by JT8D-17** [comment] 2020-06-30 15:45
Makes sense and sounds good.

**Comment by mSparks43** [comment] 2021-01-03 05:23
partially done for the next release. not quite everything I would want but closing this until there is more detail sent plugin side to control them more precisely

**Closed by mSparks43** 2021-01-03 05:23 UTC
