### ISSUE TITLE
Android App Landscape layout issue

### ISSUE THREAD

**Issue by Devirex** [mSparks43/XPlane-11-AutoATC-plugin#29] opened 2019-10-12 20:28 UTC
The android app in landscape mode has following issue:
If you click the the "command" button the layout switches from landscape to portrait and back to landscape without triggering recording.  
![bug](https://user-images.githubusercontent.com/6270055/66707361-831dc680-ed3f-11e9-8f0b-3ca4bb8b9e40.gif)

**Comment by mSparks43** [comment] 2019-10-13 04:32
Well thats... ridiculous. There's an update in the pipeline for the next 24 hours, should be fixed in that assuming its easily recreatable and caused by what I think it is.

**Comment by mSparks43** [comment] 2019-10-13 05:09
Also found and fixed another bug whereby it could lock in the orientation and refuse to rotate afterwards. Both should be fixed in version 0.8.7.074, but there's some Android fragmentation issues I also had to work around (the source of the above behaviour) so might take more than one go.

**Closed** 2019-11-18 23:28 UTC
Labels: In Beta, bug
