### ISSUE TITLE
Taxi Errors

### ISSUE THREAD

**Issue by oriontribunal** [mSparks43/XPlane-11-AutoATC-plugin#15] opened 2019-04-09 15:23 UTC
KSFO Taxi to 28L via Z U C causes aircraft to turn on 1R/19L instead of crossing 1L/1R on C toward the end of 28L. This puts them in the mother of all bad places, pretty much where 28L/R, and 1L/R all converge with their wonderful # sign configuration. It considers this place to be the hold short of 28L, and then when instructed to take the runway, they taxi down 28L and turn around at the end.

Some aircraft are also confused as to the frequency they are on. One of them contacted the tower for taxi clearance [on the gnd frequency], and ground gave it instead of saying... wrong frequency or "this is ground."

**Comment by mSparks43** [comment] 2019-04-09 22:32
KSFO is going to be one of the "problem" ones.
What a maze...
Couple of things I notice / thoughts (which I'll have to test when developing airport procedures further)
* Possibly leaving rogue taxi nodes on the runway
* missing definitions of taxiway/runways
* Really looking like the best way forward will be to pull airport map data out of OSM, and this is going to have to be a priority for future AI server updates 
* AI planes need to always hold short of runways
* While AI planes re routing to sneak a round each other is mildly amusing, more complex (insane) airports like this are going to need some conversation and special attention around operational safety

KSFO gets special mention in SOIA proceedures
https://www.faa.gov/air_traffic/publications/media/AIP_amd2_dtd_12_10_2015.pdf

**Comment by mSparks43** [comment] 2019-07-11 10:28
gridlock at Gatwick
https://www.youtube.com/watch?v=In0Yq4nWfLs

**Comment by mSparks43** [comment] 2019-10-13 05:34
![S-76C - 2019-10-13 07 26 15](https://user-images.githubusercontent.com/6773686/66711375-e719ac80-ed8a-11e9-8f4c-f793bd3ba7e5.png)
As Flight model (FM) and taxi improvements have gone in, these kind of bugs are getting more rational. The above gridlock is caused by approving start/up and taxi when doing so will cause a taxiway way conflict. 

One of the "best" answers I got to one of my questions to the ATC guys was "if people aren't exactly following given instructions just let them continue as long as its safe to do so".

Identifying those "not safe" circumstances is now getting reasonably close to development, allowing startup when not safe is exactly one of those circumstances, so this should resolve itself during development eventually.

**Comment by mSparks43** [comment] 2019-10-23 08:42
https://www.youtube.com/watch?v=A85gxiMIuQk

Video of the new taxi improvements. Last one to fix which should get this running like absolute clockwork is to reduce the time between an aircraft taking off and issuing lineup instructions to the next in line.

WontFix the collision at 18 minutes 30 seconds for now.

**Comment by mSparks43** [comment] 2019-10-27 07:50
Debug this plane (caught flying underground, possibly bad frequency related?):
activating lufthansa fower wun two two
plane lufthansa fower wun two two  Set airframe=CRJ9 Bydgoszcz Ignacy Jan Paderewski Airport:Frankfurt am Main Airport
lufthansa fower wun two two  becomes active in 1.2456333333333334 minutes.
2019/10/26 20:24:31:bydgoszcz-ignacy:Approved lufthansa fower wun two two on 21 startup 1 in queue pos:0
2019/10/26 20:26:31:bydgoszcz-ignacy:released lufthansa fower wun two two on 21 startup 0 waiting
2019/10/26 20:26:51:bydgoszcz-ignacy:Approved lufthansa fower wun two two on 21 taxiway 1 in queue pos:0
lufthansa fower wun two two  ai plane hasn't been heard for 7200072
dropping ai lufthansa fower wun two two from active Flights:ai46012438-46012438
2019/10/26 22:23:47:bydgoszcz-ignacy:released lufthansa fower wun two two on 21 taxiway 0 waiting

**Comment by mSparks43** [comment] 2019-12-19 23:15
->caught flying underground

Was bad runway altitudes. This, and known taxi errors should be fixed on the latest AI server

**Comment by mSparks43** [comment] 2020-02-05 14:36
* AI planes need to always hold short of runways
Is planned for a future language update, other bugs listed here should now be fixed/working.
Closing this issue, please open a new one for this or any other airports that have any remaining issues.

**Closed by mSparks43** 2020-02-05 14:36 UTC
Labels: Airport, In Beta
